# Generated by Django 2.2.2 on 2019-06-28 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_string', models.TextField()),
                ('time_of_announcement', models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 28, 14, 53, 23, 603609))),
            ],
        ),
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('the_file', models.FileField(blank=True, null=True, upload_to='mainapp.DocumentModel/bytes/filename/mimetype')),
                ('type_of_doc', models.CharField(choices=[('mom', 'MOM'), ('sem', 'SEM'), ('other', 'OTHER')], default='other', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agenda', models.TextField()),
                ('time_of_meeting', models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 28, 14, 53, 23, 603609))),
            ],
        ),
    ]
