# Generated by Django 2.2.2 on 2019-06-19 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_string', models.TextField()),
                ('time_stamp', models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 19, 15, 51, 27, 136886))),
            ],
        ),
    ]
