# Generated by Django 2.2.2 on 2019-06-19 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='time_stamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 19, 18, 12, 49, 514864)),
        ),
    ]
