# Generated by Django 2.2.2 on 2019-06-20 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190619_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='time_stamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 20, 9, 15, 37, 902795)),
        ),
    ]
