# Generated by Django 2.2.2 on 2019-06-20 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190620_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='time_stamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 20, 15, 7, 38, 26300)),
        ),
    ]
