# Generated by Django 2.2.2 on 2019-06-20 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190620_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_string', models.TextField()),
                ('time_stamp', models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 20, 15, 13, 19, 347620))),
            ],
        ),
        migrations.DeleteModel(
            name='Announcements',
        ),
    ]
