# Generated by Django 2.2.2 on 2019-06-20 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20190620_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='picture',
            new_name='the_file',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='time_of_announcement',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 20, 21, 15, 0, 712460)),
        ),
    ]
