# Generated by Django 2.2.2 on 2019-06-23 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20190623_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_string', models.TextField()),
                ('time_of_meeting', models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 23, 21, 7, 14, 543508))),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='time_of_announcement',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 23, 21, 7, 14, 543508)),
        ),
    ]
