# Generated by Django 2.2.2 on 2019-06-24 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_auto_20190624_0058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentModel',
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='time_of_announcement',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 24, 21, 9, 53, 45368)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_of_meeting',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 24, 21, 9, 53, 46365)),
        ),
    ]
