# Generated by Django 2.2.2 on 2019-06-26 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_auto_20190626_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='type_of_doc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='time_of_announcement',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 26, 23, 2, 13, 455809)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_of_meeting',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 26, 23, 2, 13, 455809)),
        ),
    ]
