# Generated by Django 2.2.2 on 2019-06-26 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_auto_20190626_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='time_of_announcement',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 26, 23, 25, 39, 839944)),
        ),
        migrations.AlterField(
            model_name='documents',
            name='type_of_doc',
            field=models.CharField(choices=[('mom', 'MOM'), ('sem', 'SEM'), ('other', 'OTHER')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_of_meeting',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 26, 23, 25, 39, 840973)),
        ),
    ]
