# Generated by Django 2.2.2 on 2019-06-26 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_auto_20190626_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='text_string',
            new_name='Agenda',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='time_of_announcement',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 26, 23, 52, 2, 506641)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_of_meeting',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 6, 26, 23, 52, 2, 506641)),
        ),
    ]
