# Generated by Django 2.2.2 on 2019-06-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Quisquam Consectetur', max_length=120)),
                ('post', models.CharField(max_length=120)),
                ('group', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('year', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'First Year Btech'), (2, 'Second Year Btech'), (3, 'Third Year Btech'), (4, 'Fourth Year Btech'), (5, 'PG'), (6, 'PhD'), (None, 'Not Applicable')], null=True)),
                ('image', models.CharField(default='https://via.placeholder.com/150', max_length=200)),
                ('linkedin', models.CharField(default='#', max_length=200)),
                ('facebook', models.CharField(default='#', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
