# Generated by Django 2.2.2 on 2019-06-17 13:07

import os
from django.db import migrations
from django.core import serializers
import json

print(os.getcwd())
def add_data(apps, schema_editor):
    with open('team/members.json') as data:
        for deserialized_object in serializers.deserialize("json", data):
            deserialized_object.save()



class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_data)
    ]
